package com.sampling.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sampling.Beans.SamplingBean;
import com.sampling.Beans.Dictionary;

import com.sampling.dao.SamplingBeanDao;
import com.sampling.dao.DictionaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig samplingBeanDaoConfig;
    private final DaoConfig dictionaryDaoConfig;

    private final SamplingBeanDao samplingBeanDao;
    private final DictionaryDao dictionaryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        samplingBeanDaoConfig = daoConfigMap.get(SamplingBeanDao.class).clone();
        samplingBeanDaoConfig.initIdentityScope(type);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        samplingBeanDao = new SamplingBeanDao(samplingBeanDaoConfig, this);
        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);

        registerDao(SamplingBean.class, samplingBeanDao);
        registerDao(Dictionary.class, dictionaryDao);
    }
    
    public void clear() {
        samplingBeanDaoConfig.clearIdentityScope();
        dictionaryDaoConfig.clearIdentityScope();
    }

    public SamplingBeanDao getSamplingBeanDao() {
        return samplingBeanDao;
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

}
