package com.sampling.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sampling.Beans.Dictionary;
import com.sampling.Beans.SamplingBean;

import com.sampling.dao.DictionaryDao;
import com.sampling.dao.SamplingBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dictionaryDaoConfig;
    private final DaoConfig samplingBeanDaoConfig;

    private final DictionaryDao dictionaryDao;
    private final SamplingBeanDao samplingBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        samplingBeanDaoConfig = daoConfigMap.get(SamplingBeanDao.class).clone();
        samplingBeanDaoConfig.initIdentityScope(type);

        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);
        samplingBeanDao = new SamplingBeanDao(samplingBeanDaoConfig, this);

        registerDao(Dictionary.class, dictionaryDao);
        registerDao(SamplingBean.class, samplingBeanDao);
    }
    
    public void clear() {
        dictionaryDaoConfig.clearIdentityScope();
        samplingBeanDaoConfig.clearIdentityScope();
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

    public SamplingBeanDao getSamplingBeanDao() {
        return samplingBeanDao;
    }

}
